use a real temporary directory for test secrets
linux-system-roles/ha_cluster pull request #65
Opened 2022-09-19 17:27 UTC by richm

The tests were writing generated secrets to the directory tests/tmp
which is shared by all tests when running tests in parallel.
Instead, create a real temporary directory for these secrets for the
tests that use generated secrets.

2022-09-19 17:27 UTC, richm commented
[citest]

2022-09-19 21:03 UTC, richm commented
[citest]

2022-09-19 22:48 UTC, nhosoi approved these changes
lgtm

2022-09-20 07:51 UTC, spetrosi approved these changes
lgtm

2022-09-20 08:57 UTC, tomjelinek requested changes
Thank you for fixing this issue!

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_custom_pcsd_tls.yml
> +          delegate_to: localhost
```suggestion
          delegate_to: localhost
          run_once: true
```
I'm running the test on a two-node cluster. Without `run_once: true`, each node gets a different work directory path, and the test fails.

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_custom_pcsd_tls.yml
> +            state: absent
```suggestion
            state: absent
          delegate_to: localhost
          run_once: true
```
Clean the directory on the controller where it actually is created.

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_existing_psks.yml
> +          delegate_to: localhost
```suggestion
          delegate_to: localhost
          run_once: true
```

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_existing_psks.yml
> +            state: absent
```suggestion
            state: absent
          delegate_to: localhost
          run_once: true
```

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_new_psks.yml
> +            state: absent
```suggestion
            state: absent
          delegate_to: localhost
          run_once: true
```

2022-09-20 08:57 UTC, tomjelinek commented on tests/tests_cluster_basic_new_psks.yml
> +          delegate_to: localhost
```suggestion
          delegate_to: localhost
          run_once: true
```

2022-09-20 13:34 UTC, richm commented
[citest]

2022-09-20 13:49 UTC, tomjelinek approved these changes

2022-09-20 17:57 UTC, merged